### ISSUE TITLE
Pantheon Creation - Hades

### ISSUE THREAD

**Issue by LordEggNutz** [LordEggNutz/Imrallon#12]
Need to complete creating the pantheon for Imrallon.  This will include histories of each of the First Twelve and how they came to be deities.

** Hades ** - General of the Armies of the Underworld
- [x] History
- [x] Followers
- [x] Favored Race?

- [X] Alignment:
- [X] Favored Weapon:	
- [X] Favored Animal:	
- [X] Symbol: 
- [X] Portfolio: 
- [X] Domains: 
- [X] Description:

**Comment by LordEggNutz** [comment]
Alignment: LG	
Favored Weapon: Greatsword	
Favored Animal: Eagle	
Symbol: Lightning bolt	
Portfolio: God of the sky, weather, order, and lightning; king of the gods	
Domains: Air, Balance, Charm, Glory, Law, Nobility, Pride, Sky, Strength, Weather.			
Description: King of the gods and ruler of Mount Olympus; god of the sky, lightning, thunder, law, order, justice. Youngest child of the Titans Cronus and Rhea. Symbols include the thunderbolt, eagle, oak tree, scepter, and scales. Brother and husband of Hera, although he had many lovers, also brother of Poseidon, Hades, Demeter, and Hestia

**Comment by LordEggNutz** [comment]
Alignment: LE	
Favored Weapon: Helmet
Favored Animal: Cerebus	
Symbol: Three-headed cerebus	
Portfolio: God of the underworld, death, the undead, and forbidden riches	
Domains: Darkness, Death, Decay, Greed, Law, Necromancy, Pestilence, Shadow, Undeath			
Description: God of the Underworld, dead and the riches under the Earth; he was born into the first Olympian generation, the elder brother of Zeus, Poseidon, Hera, and Demeter, and younger brother of Hestia, but as he lives in the Underworld rather than on Mount Olympus, he is typically not included amongst the twelve Olympians.

**Comment by LordEggNutz** [comment]
Hades is the eldest son of the Titans Cronus and Rhea. During the Titan Wars, Hades fought on the side of the Titans with his armies of the Underworld.  However, during the war, he watched Cronos devour his sisters Hestia and Demeter.  After this event, he sought after his younger brothers Zeus and Poseidon. He offered to switch sides and fight along side them under the condition that he remain the ruler of the Underworld and that he would be free to impose his own will upon his Realm.  Zeus and Poseidon agreed with the caveat that Hades free thier sisters first.

Hades agreed to this and proceeded to craft a poison from a mix of poppy seed and cyprus root.  The poison would cause his father to disgorge his sisters.  Immediately afterwards, Hades swooped them up and fled to be by Zeus's side.  Once he rescued them and the three brothers were together, Hades drew up a contract for the division of the cosmos for after their victory.  In this contract, Zeus would rule the heavens and air, Poseidon would rule the seas and Hades would remain as lord of the Underworld.  The contract went on to state that they were forbidden from taking any actions in the others respective realms.  Just as the contract was agreed to and signed, Cronos struck down his eldest son and sent him back into the Underworld.  

Once again, Rhea interceded on her son's behalf.  She travelled to the Underground and revived Hades.  He retured to the earth with a vengeance now.  His contract was validated and he joined the fight against his father and the other Titans.  His army, as with the other Titans, mainly consided of other dragons and drakes.  However, his daughters, the Erinyes would soon join his side as well.  

During the war, Hades battled with the Titan Lapetus on multiple occasions.  In their final battle, Hades in dragon form, tore the heart of Lapetus from his chest and ate it.  With this act, Hades exercised his power as first born Titan to absorbed the portfolio of Mortality that Lapetus once had. This assault on Lapetus was intentional and he was targeted by Hades specifically due to this portfolio.  With the control over Mortality and as Lord of the Underworld, Hades indeed had power over the dead and dying.

When the Titan Wars was over, the contract took effect. Hades became Lord of the Underworld.  One of his first acts, based on actions during the war, was to construct the Veil.  The Veil is a barrier between the land of the living and the dead.  It prevented those that have parted from coming back.  This upset Prometheus since it obstructed his Magic.  In turn, he allowed Magic to bring back the dead by temporarily perforating the Veil.  Although angered by this act, Hades eventually agreed and now allows this.  However, he loathes the Undead and the use of them.  He is in constant conflict with Hecate, the Mistress of the Undead and his occasional lover.

**Comment by LordEggNutz** [comment]
Followers of Hades are undertakers, dealers in dead, death cults and enemies of the Undead.

**Comment by LordEggNutz** [comment]
Hades has no favored race as Death does not play favorites.  All are equal in the eyes of Hades.

**Comment by Mklj0** [comment]
I think it's a good bit done.

**Comment by LordEggNutz** [comment]
Added to pull and website
greater-pantheon-updates #13 
http://lordeggnutz.com/imrallon/2017/11/02/hades-lord-of-the-underworld/
