### ISSUE TITLE
Pantheon Creation - Poseidon

### ISSUE THREAD

**Issue by LordEggNutz** [LordEggNutz/Imrallon#3]
Need to complete creating the pantheon for Imrallon.  This will include histories of each of the First Twelve and how they came to be deities.

** Poseidon** - General of the Armies of the Seas
- [x] History
- [x] Followers
- [x] Favored Race?

- [X] Alignment:
- [X] Favored Weapon:	
- [X] Favored Animal:	
- [X] Symbol: 
- [X] Portfolio: 
- [X] Domains: 
- [X] Description:

**Comment by LordEggNutz** [comment]
Alignment: CN	
Favored Weapon: Trident	
Favored Animal: Dolphin, Horse	
Symbol: Trident and Waves	
Porfolio: God of the seas
Domains: Chaos, Weather, Strength, Water
Description: God of the seas, earthquakes, and tidal wave. Symbols include the horse, bull, dolphin, and trident. Middle son of Cronus and Rhea. Brother of Zeus and Hades. Married to the Nereid Amphitrite, although, like most male Greek Gods, he had many lovers.

**Comment by LordEggNutz** [comment]
Alignment: CN	
Favored Weapon: Trident	
Favored Animal: Dolphin, Horse	
Symbol: Trident and Waves	
Porfolio: God of the seas
Domains: Chaos, Weather, Strength, Water
Description: God of the seas, earthquakes, and tidal wave. Symbols include the horse, bull, dolphin, and trident. Middle son of Cronus and Rhea. Brother of Zeus and Hades. Married to the Nereid Amphitrite, although, like most male Greek Gods, he had many lovers.

**Comment by LordEggNutz** [comment]
Favored Race: Merfolk

**Comment by LordEggNutz** [comment]
Poseidon was born amid a field of sheep.  His mother, Rhea, hid his birth from his father, Cronus, for fear that he would destroy him.  This proved to be true as Rhea presented Cronus with a baby horse, in which he promptly devoured.  Afterwards, Rhea gave Poseidon to a shepherd family to raise.  The family lived on the island of Chourns and the ocean had always facinated Poseidon.  Unlike his siblings, Poseidon knew of his parentage and knew that his father wanted him dead.  He kept a low profile as to not draw the attention of the Titans and their wrath.  However, it seemed that Poseidon was so intrinsically tied to the sea that he seemed to affect it.  When Poseidon would be angered or upset, the sea would whip up and a storm would hit the island.  Alternatively, when Poseidon was pleased or content, the seas would be fair and calm.

As he got older, Poseidon became a fisherman and would head out on the boats to catch fish for the island.  Soon the other fisherman began to notice that the seas reacted to Poseidon.  They began to praise him and keep him in good spirits as to keep the seas happy as well.  Unfortunately, this did not always happen.  One day, he was out on the boat when a storm hit.  Poseidon was cast from the boat and lost at sea.  His parents, the shepards that raised him, could not believe this.  They knew it would take more than a small storm to kill their son.  For 2 months, they walked along the shoreline and sent out bottled messages for him to return home.  

Poseidon was rescued by the Nereid, a race of sea nymphs. He was so gracious for this that he betrothed the nereid Amphitrite and took her as his wife.  One the two month date of his accident, Poseidon and Amphitrite left the ocean and went back home.  As they walked onto the shore, they were met by his parents and other islanders.  They threw a party for the new couple.  The story of his accident and coming back is what caught the ear of Zeus when he was planning his war on the Titans.

Zeus approached Poseidon and proposed that he be a general in the war he was planning.  Since he was still upset about the assassination attempt by his father, Poseidon joined as the General of the Seas.  He gathered the Nereid and merfolk and joined in the fight against the Titans.

After the Titan War was over, Poseidon returned to Chourns and his bride.  Over time, he has taken on a multitude of other lovers, both male and female.  Also like his brother Zeus, he had fathered a great number of children as well.  However, Amphitrite remained by his side.  Rumor also suggest that she had taken on lovers during the war as well.

**Comment by LordEggNutz** [comment]
Followers of Poseidon are sailors, fishermen, Nereid, merfolk and those that make a living on or near the sea.

**Comment by LordEggNutz** [comment]
@Mklj0 @MentalCappedGamer for review

**Comment by Mklj0** [comment]
I find the current information suitable.

**Comment by LordEggNutz** [comment]
Added to greater-pantheon-updates pull

**Comment by LordEggNutz** [comment]
http://lordeggnutz.com/imrallon/2017/10/31/poseidon-god-the-sea/
