### ISSUE TITLE
Pantheon Creation - Ares

### ISSUE THREAD

**Issue by LordEggNutz** [LordEggNutz/Imrallon#8]
Need to complete creating the pantheon for Imrallon.  This will include histories of each of the First Twelve and how they came to be deities.

** Ares ** - 
- [x] History
- [x] Followers
- [x] Favored Race?

- [X] Alignment:
- [X] Favored Weapon:	
- [X] Favored Animal:	
- [X] Symbol: 
- [X] Portfolio: 
- [X] Domains: 
- [X] Description:

**Comment by LordEggNutz** [comment]
Alignment: CE	
Favored Weapon: Longspear	
Favored Animal: Dog	Vulture 
Symbol: Clawed spear and shield	
Portfolio: God of war, combat, and arms	
Domains: Chaos, Courage, Destruction, Glory, Madness, Pride, Strength, War, Wrath.			
Description: God of war, violence, and bloodshed. Symbols include the boar, serpent, dog, vulture, spear, and shield. Son of Zeus and Hera, all the other gods (except Aphrodite) despised him. His Latin name, Mars, gave us the word "martial."

**Comment by LordEggNutz** [comment]
Favored Race: Orc ... Yes the war-loving Orcs, we all know and love

**Comment by LordEggNutz** [comment]
Ares created the Orcs and imbued them with their innate blood lust.
Idea 1:  They were formed from earth that was consecrated with blood and semen
Idea 2:  They were formed from the ground where virgin sacrifices were performed
Idea 3:  They were formed from a piece of his heart and iron forged by Hephestus

**Comment by LordEggNutz** [comment]
Ares was born from Zeus and Hera.  The middle child was born during the opening of Battle of Escrutia Ridge.  The armies of Zeus and Hera were enganged with the Titan Hyperion and his army of drakes.  The pregnant Hera gave birth on the battlefield and Ares was born in the blood and gore of friend and foe alike.  From that day on, Ares was obsessed with battle and killing.  He trained and mastered, along with his sister Athena, all of the martial arts.  However the two differred in thier point of view for war.  While Athena studied under Zeus in matters of planning and tactics, Ares revelled in the battle itself.  On the battlefield, Ares would be seen bathed in blood and charging into battle on his war chariot. 

Not unlike his father, Ares had a multitude of lovers.  With his sister, Aphrodite, he had twin sons Phobos and Deimos.  He raised and trained them to be just as overwhelming, insatiable and destructive in battle as he was.  However, due to the love of thier mother, they did not get entirely consumed as Ares did.  Nonetheless, the trio of father and sons decimated thier enemies.

Ares learned that Hephestus created his dwarves to help him with his tasks and Ares sought the same for his soldiers.  The army that he had needed constant replacement and he devised a way to create creatures that would breed like vermin and would have the same skill, and bloodlust, as he did.  Hephestus assisted him with the forging of iron, to signify strength, that he would use in his ritual.  To impart a little bit of himself, he cut off a piece of his heart.  The ritual created the race of orcs and they indeed proved to be highly skilled in battle and had the insatiable bloodlust of Ares.

After the Titan Wars, the orcs remained on the world and continued to worship Ares.  The other gods and goddess were concerned with the violence and evil that Ares and his orcs possessed.  However, any retribution against them was tempered by the daughter of Ares and Aphrodite, Adrestia.  Adrestia implored that her father and the orcs were needed to balance the scales and any attempt at retribution against either of them would result in catastrophic devastation.  The argument satisfied Zeus and the others.  Ares and Aphrodite were so pleased in their daughter that she was given the portfolio of Balance and made a goddess.

**Comment by LordEggNutz** [comment]
@Mklj0 @MentalCappedGamer 

What do you think of this bio for Ares?

**Comment by Mklj0** [comment]
I find the new information suitable.

**Comment by LordEggNutz** [comment]
Added to greater-pantheon-updates pull

**Comment by LordEggNutz** [comment]
http://lordeggnutz.com/imrallon/2017/10/31/ares-god-of-war/
